# Database
db.host=localhost
db.port=5432
db.name=volabyte
db.user=postgres
db.password=password
spring.datasource.url=jdbc:postgresql://${db.host}:${db.port}/${db.name}
spring.datasource.username=${db.user}
spring.datasource.password=${db.password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/changelog-root.xml
