-- liquibase formatted sql

-- changeset Robin.Mayer:1753078054-1
create table users
(
    id            bigint generated by default as identity primary key,
    created_at    timestamp(6),
    display_name  varchar(255),
    last_login_at timestamp(6),
    password      varchar(255),
    role          varchar(255)
        constraint users_role_check
            check ((role)::text = ANY ((ARRAY ['USER'::character varying, 'ADMIN'::character varying])::text[])),
    user_id       varchar(255),
    user_name     varchar(255)
);
