-- liquibase formatted sql

-- changeset Robin.Mayer:1755346255-1
ALTER TABLE users ALTER COLUMN user_id TYPE varchar(36);

-- changeset Robin.Mayer:1755346255-2
create table files
(
    id                  bigint generated by default as identity primary key,
    name                varchar(255) NOT NULL,
    is_directory        boolean NOT NULL,
    referenced_file     varchar(255) CONSTRAINT files_referenced_file_unique UNIQUE,
    parent_directory_id bigint,
    owner_id            varchar(36) NOT NULL,
    uploaded_at         timestamp(6) NOT NULL
);