-- liquibase formatted sql

-- changeset Robin.Mayer:1756524503-1
CREATE TABLE refresh_tokens
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     varchar(36) NOT NULL,
    token       varchar(255) NOT NULL,
    expires_at  timestamp(6) NOT NULL
);