-- liquibase formatted sql

-- changeset Robin.Mayer:1756524503-1
CREATE TABLE sessions
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         varchar(36) NOT NULL,
    device_id       varchar(36) NOT NULL CONSTRAINT sessions_device_id_unique UNIQUE,
    device_name     varchar(255) NOT NULL,
    refresh_token   varchar(128) NOT NULL CONSTRAINT sessions_refresh_token_unique UNIQUE,
    expires_at      timestamp(6) NOT NULL
);